# nspt group configuration
# You can configure nspt for your group here.
#
# Example: list the files you want to share with your group
#   files = [
#     { name = "baseenv",        path = "./.env" },
#     { name = "envforproduction",   path = "./.env.prod" },
#     { name = "frontendconfig",  path = "./frontend/config.yml" },
#   ]

group = "myteam"
files = []
