# nspt group configuration
# You can configure nspt for your group here.
#
# Example: list the files you want to share with your group
#   files = [
#     { name = ".env",        path = "./.env" },
#     { name = ".env.prod",   path = "./.env.prod" },
#     { name = "config.yml",  path = "./config/config.yml" },
#   ]

group = "hehe"
files = []
