Output addd_teammate.gif
Set Shell "zsh"
Set FontSize 16
Set Width 600
Set Height 390
Set Theme "GitHub Dark"
Set WindowBar Colorful
Set Padding 20
Set TypingSpeed 70ms
Set Margin 20
Set MarginFill "#0d1117"
Set BorderRadius 10

Sleep 1s
Type "nspt"
Sleep 500ms
Enter
Sleep 1.5s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 800ms
Enter
Sleep 500ms

Down
Sleep 500ms
Up
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Type "amezan-adhikari"
Sleep 1s
Enter
Sleep 2s
Enter
Sleep 1s
